#!/usr/bin/sh

export BSPDIR="$HOME/.config/bspwm"
export SXDIR="$HOME/.config/sxhkd"

export BSPCFG="$BSPDIR/bspwmrc"
export SXCFG="$SXHKDIR/sxhkdrc"

export WALLBG="$HOME/Pictures/wall-img"

sxhkd &
feh --bg-center $WALLBG
picom &
dunst &

bash $HOME/.config/polybar/launch.sh

# TODO： add input method

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off