#!/usr/bin/sh

export XDG_SESSION_DESKTOP="bspwm"
. $HOME/.xprofile

export BSPDIR="$HOME/.config/bspwm"
export SXDIR="$HOME/.config/sxhkd"

export BSPCFG="$BSPDIR/bspwmrc"
export SXCFG="$SXDIR/sxhkdrc"

export WALLBG="$HOME/Pictures/wall-img"

xrdb -merge ~/.Xresources

sxhkd &
copyq &
feh --bg-center $WALLBG
picom &
dunst &
clash-verge &
nm-applet &

bash $HOME/scripts/touchpad-scroll.sh

bash $HOME/.config/polybar/launch.sh

setxkbmap -option caps:hyper


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a copyq state=floating
bspc rule -a zenity state=floating
bspc rule -a scrcpy state=floating
bspc rule -a clash-verge desktop='^9'
bspc rule -a "实时字幕" state=floating follow=on
